### ISSUE TITLE
Error with the first example of the doc

### ISSUE THREAD

**Issue by sbusso** [IPGeolocation/ip-geolocation-api-javascript-sdk#5]
In the first example of the sdk `console.log(ipgeolocationApi.getGeolocation());` it cant work as default params is null and then it calls `getIps` from null.

https://github.com/IPGeolocation/ip-geolocation-api-javascript-sdk/blob/d4452dae34b857f4fcf3bf2a39c7916d79b8439e/IPGeolocationAPI.js#L15

**Comment by usmanbinliaqat** [comment]
> In the first example of the sdk `console.log(ipgeolocationApi.getGeolocation());` it cant work as default params is null and then it calls `getIps` from null.
> 
> [ip-geolocation-api-javascript-sdk/IPGeolocationAPI.js](https://github.com/IPGeolocation/ip-geolocation-api-javascript-sdk/blob/d4452dae34b857f4fcf3bf2a39c7916d79b8439e/IPGeolocationAPI.js#L15)
> 
> Line 15 in [d4452da](/IPGeolocation/ip-geolocation-api-javascript-sdk/commit/d4452dae34b857f4fcf3bf2a39c7916d79b8439e)
>  if(params.getIps()) {

Resolved.
As `ipAddresses` is an array, so it should be an empty array by default and not the null. Please download the latest SDK and test if it works for you.
