### ISSUE TITLE
Bug: unhandled exception

### ISSUE THREAD

**Issue by fbadiola** [IPGeolocation/ip-geolocation-api-javascript-sdk#6]
Hi all,

I found an unhandled exception when executing `JSON.parse` [here](https://github.com/IPGeolocation/ip-geolocation-api-javascript-sdk/blob/master/IPGeolocationAPI.js#L134). A few days ago, API dosn't return a json valid text and it broke services that use it.

Do you accept PRs to fix it?

Regards.

**Comment by ejaz-ahmed** [comment]
@usmanl @munawarJF please look into this issue.

**Comment by usmanl** [comment]
@fbadiola we accept PRs for fixing the issues. JSON parsing exception hasn't been handled here, considering the perfect response from API.
